#!/usr/bin/env python3
"""Refresh videos.js with YouTube search results for all things sump.

Run whenever the rotation feels stale: python3 scripts/refresh_playlist.py
Requires yt-dlp on PATH. Output is a JS file (not JSON) so the site also
works without fetch(). One search query caps out at a few hundred results,
so we mine many sump-adjacent queries and dedupe by video id.
"""
import json
import subprocess
import sys
import time
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

# every angle of sump: basements, aquariums, engines, mines, doom metal
QUERIES = [
    "sump", "sump pump", "sump pit", "sump basin", "basement sump",
    "sump pump install", "sump pump replacement", "sump battery backup",
    "aquarium sump", "reef sump", "sump tank", "sump filter", "diy sump",
    "koi pond sump", "sump refugium", "sump baffle",
    "oil sump", "engine sump", "car sump", "sump plug", "sump guard",
    "mining sump", "sump cleaning", "sump overflow", "sumping",
]
PER_QUERY = 300
MIN_SEC = 20      # skip near-empty clips
MAX_SEC = 1800    # skip the 10-hour sump-noise loops so they can't eat the schedule
REQUIRE_SUMP_IN_TITLE = True  # fuzzy search drifts; the broadcast stays pure

OUT = Path(__file__).resolve().parent.parent / "videos.js"


def search(query: str) -> list[dict]:
    proc = subprocess.run(
        ["yt-dlp", "--flat-playlist", "-j", f"ytsearch{PER_QUERY}:{query}"],
        capture_output=True, text=True,
    )
    entries = []
    for line in proc.stdout.splitlines():
        try:
            entries.append(json.loads(line))
        except json.JSONDecodeError:
            continue
    print(f"  '{query}': {len(entries)} results")
    return entries


def main() -> int:
    print(f"mining {len(QUERIES)} sump veins x {PER_QUERY} (takes a few minutes)...")
    with ThreadPoolExecutor(max_workers=4) as pool:
        batches = list(pool.map(search, QUERIES))

    seen: set[str] = set()
    videos = []
    skipped = 0
    for batch in batches:
        for e in batch:
            vid = e.get("id")
            dur = e.get("duration")
            title = (e.get("title") or "").strip()
            if not vid or vid in seen:
                continue
            seen.add(vid)
            if e.get("live_status") == "is_live" or dur is None:
                skipped += 1
                continue
            if not (MIN_SEC <= dur <= MAX_SEC):
                skipped += 1
                continue
            if REQUIRE_SUMP_IN_TITLE and "sump" not in title.lower():
                skipped += 1
                continue
            videos.append({"id": vid, "title": title, "duration": int(dur)})

    if len(videos) < 10:
        print(f"only {len(videos)} usable videos found; not overwriting", file=sys.stderr)
        return 1

    total = sum(v["duration"] for v in videos)
    payload = {
        "generated": time.strftime("%Y-%m-%d", time.gmtime()),
        "query": " | ".join(QUERIES),
        "videos": videos,
    }
    OUT.write_text(
        "// generated by scripts/refresh_playlist.py -- do not edit by hand\n"
        "window.SUMP = " + json.dumps(payload, ensure_ascii=False) + ";\n"
    )
    print(f"wrote {OUT.name}: {len(videos)} sumps, {total / 3600:.1f}h of footage "
          f"({skipped} skipped of {len(seen)} unique)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
